[package]
name = "piru"
description = "A game engine built around a custom scripting language meant to make smooth, performant multiplayer as simple as possible."

version.workspace = true
edition.workspace = true
repository.workspace = true
include.workspace = true

[dependencies]
colog = "1.4.0"
log.workspace = true
pollster = "1.0.1"
wgpu.workspace = true
winit.workspace = true

[lints]
workspace = true
